spring.application.name=demo

server.port=${PORT:8080}

spring.main.banner-mode=off
logging.level.org.springframework=INFO

# Database Configuration
spring.datasource.url=jdbc:postgresql://dpg-d6kk9jqli9vc73fa3cp0-a/database_setg
spring.datasource.username=database_setg_user
spring.datasource.password=glMYt4gvUduInME1eHcnEdy320Ub2tqb
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Actuator Configuration
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always